### ISSUE TITLE
Define DB content

### ISSUE THREAD

**Issue by razvanionescu26** [razvanionescu26/pssc#4]
* create an overview of the DB that is required for application
* define what data needs to be stored in each table (containing fields and limitations on each field)
* define the relationships between tables

**Comment by razvanionescu26** [comment]
After the database overview is done, we can sync and decide if changes are needed to be made.

**Comment by DenisaIovin** [comment]
![Image](https://github.com/razvanionescu26/pssc/assets/126767150/1eaa35eb-f2c4-425c-bb6d-7e4905981bf9)
